"""récreation de la bdd vers mysql

Revision ID: 141b2c147628
Revises: 
Create Date: 2025-08-06 10:45:41.935329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141b2c147628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date_limite', sa.Date(), nullable=False),
    sa.Column('id_poste', sa.Integer(), nullable=False),
    sa.Column('id_contrat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contrat'], ['contrat.id'], ),
    sa.ForeignKeyConstraint(['id_poste'], ['poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detailPostuler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_depot', sa.Date(), nullable=False),
    sa.Column('id_candidat', sa.Integer(), nullable=False),
    sa.Column('id_offre', sa.Integer(), nullable=True),
    sa.Column('id_poste', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id'], ),
    sa.ForeignKeyConstraint(['id_offre'], ['offre.id'], ),
    sa.ForeignKeyConstraint(['id_poste'], ['poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailPostuler')
    op.drop_table('offre')
    # ### end Alembic commands ###
