"""init mysql tables

Revision ID: 5ff28b32792d
Revises: 141b2c147628
Create Date: 2025-08-06 10:54:08.835559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ff28b32792d'
down_revision: Union[str, Sequence[str], None] = '141b2c147628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailPostuler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_depot', sa.Date(), nullable=False),
    sa.Column('id_candidat', sa.Integer(), nullable=False),
    sa.Column('id_offre', sa.Integer(), nullable=True),
    sa.Column('id_poste', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id'], ),
    sa.ForeignKeyConstraint(['id_offre'], ['offre.id'], ),
    sa.ForeignKeyConstraint(['id_poste'], ['poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detailpostuler')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailpostuler',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date_depot', sa.DATE(), nullable=False),
    sa.Column('id_candidat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_offre', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_poste', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_candidat'], ['candidat.id'], name=op.f('detailpostuler_ibfk_1')),
    sa.ForeignKeyConstraint(['id_offre'], ['offre.id'], name=op.f('detailpostuler_ibfk_2')),
    sa.ForeignKeyConstraint(['id_poste'], ['poste.id'], name=op.f('detailpostuler_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('detailPostuler')
    # ### end Alembic commands ###
